### ISSUE TITLE
Error on initial setup

### ISSUE THREAD

**Issue by spacemunkay** [spacemunkay/BikeShed#109]
When performing the following from the readme:

`docker-compose run web rake db:create db:migrate db:seed`

It errors with:

```
rake aborted!
NoMethodError: undefined method `bike_wheel_size_id=' for #<Bike:0x0055e492be73b0>
/usr/local/bundle/gems/activemodel-3.2.13/lib/active_model/attribute_methods.rb:407:in `method_missing'
/usr/local/bundle/gems/activerecord-3.2.13/lib/active_record/attribute_methods.rb:149:in `method_missing'
/usr/local/bundle/gems/factory_girl-2.6.4/lib/factory_girl/attribute_assigner.rb:14:in `block (2 levels) in object'
/usr/local/bundle/gems/factory_girl-2.6.4/lib/factory_girl/attribute_assigner.rb:13:in `each'
/usr/local/bundle/gems/factory_girl-2.6.4/lib/factory_girl/attribute_assigner.rb:13:in `block in object'
/usr/local/bundle/gems/factory_girl-2.6.4/lib/factory_girl/attribute_assigner.rb:12:in `tap'
/usr/local/bundle/gems/factory_girl-2.6.4/lib/factory_girl/attribute_assigner.rb:12:in `object'
/usr/local/bundle/gems/factory_girl-2.6.4/lib/factory_girl/strategy/create.rb:9:in `result'
/usr/local/bundle/gems/factory_girl-2.6.4/lib/factory_girl/factory.rb:48:in `run'
/usr/local/bundle/gems/factory_girl-2.6.4/lib/factory_girl/factory_runner.rb:25:in `run'
/usr/local/bundle/gems/factory_girl-2.6.4/lib/factory_girl/syntax/methods.rb:63:in `create'
/usr/src/app/db/seeds.rb:44:in `block in <top (required)>'
/usr/src/app/db/seeds.rb:43:in `times'
/usr/src/app/db/seeds.rb:43:in `<top (required)>'
/usr/local/bundle/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
/usr/local/bundle/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `block in load'
/usr/local/bundle/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/usr/local/bundle/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:245:in `load'
/usr/local/bundle/gems/railties-3.2.13/lib/rails/engine.rb:520:in `load_seed'
/usr/local/bundle/gems/activerecord-3.2.13/lib/active_record/railties/databases.rake:347:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

Was able to resolve by running `docker-compose run web rake db:seed` again. But would like to fix the root cause.

**Comment by spacemunkay** [comment]
Fixed by https://github.com/spacemunkay/BikeShed/pull/119
